### ISSUE TITLE
Config parser raises error when option not specified

### ISSUE THREAD

**Issue by Isabella-Dineo** [ska-sa/tigger#100]
Config parser raises error when option not specified (i.e, option is None)

```
Welcome to Tigger 1.4.0
Please wait a second while the GUI starts up.
Traceback (most recent call last):
  File "/usr/bin/tigger", line 98, in <module>
    mainwin = TigGUI.MainWindow.MainWindow(None)
  File "/usr/lib/python2.7/dist-packages/TigGUI/MainWindow.py", line 89, in __init__
    self.skyplot = SkyModelPlotter(self._skyplot_stack,self);
  File "/usr/lib/python2.7/dist-packages/TigGUI/Plot/SkyModelPlot.py", line 973, in __init__
    self._livezoom = LiveImageZoom(self);
  File "/usr/lib/python2.7/dist-packages/TigGUI/Plot/SkyModelPlot.py", line 387, in __init__
    self.setPlotSize(radius,factor);
  File "/usr/lib/python2.7/dist-packages/TigGUI/Plot/SkyModelPlot.py", line 409, in setPlotSize
    Config.set('livezoom-radius',radius);
  File "/usr/lib/python2.7/dist-packages/Kittens/config.py", line 137, in set
    return self.parser.set(section or self.section, option, value, save=save)
  File "/usr/lib/python2.7/dist-packages/Kittens/config.py", line 91, in set
    if self.get(section, option) == value:
  File "/usr/lib/python2.7/dist-packages/Kittens/config.py", line 109, in get
    return self._get('get', option, default, section)
  File "/usr/lib/python2.7/dist-packages/Kittens/config.py", line 78, in _get
    self.syscp.set(section, option, str(default))
  File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 1238, in set
    _, option, value = self._validate_value_types(option=option, value=value)
  File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 1218, in _validate_value_types
```

This is the offending line

```
        if not isinstance(option, str):
            raise TypeError("option keys must be strings")
```

**Comment by sjperkins** [comment]
Any workarounds for this?

**Comment by o-smirnov** [comment]
Fixed by https://github.com/ska-sa/kittens/pull/9
