### ISSUE TITLE
lsm iterator broken

### ISSUE THREAD

**Issue by bennahugo** [ska-sa/tigger#103]
Selecting components in lsms no longer works:
```
<Tigger.Models.ModelClasses.Polarization object at 0x7fa2849b10d0>
<Tigger.Models.ModelClasses.Polarization object at 0x7fa2849b1290>
<Tigger.Models.ModelClasses.Polarization object at 0x7fa288a23f90>
<Tigger.Models.ModelClasses.Polarization object at 0x7fa288a23dd0>
<Tigger.Models.ModelClasses.Polarization object at 0x7fa2849b1090>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/TigGUI/SkyModelTreeWidget.py", line 134, in _selectionChanged
    for item in self.iterator():
TypeError: iter() returned non-iterator of type 'Iterator'
<Tigger.Models.ModelClasses.Polarization object at 0x7fa288a23f90>
<Tigger.Models.ModelClasses.Polarization object at 0x7fa288a23dd0>
<Tigger.Models.ModelClasses.Polarization object at 0x7fa288a23cd0>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/TigGUI/SkyModelTreeWidget.py", line 134, in _selectionChanged
    for item in self.iterator():
TypeError: iter() returned non-iterator of type 'Iterator'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/TigGUI/SkyModelTreeWidget.py", line 134, in _selectionChanged
    for item in self.iterator():
TypeError: iter() returned non-iterator of type 'Iterator'

```

**Comment by gijzelaerr** [comment]
@bennahugo can you verify if this solves your problem?
