### ISSUE TITLE
astro-tigger dependency problem

### ISSUE THREAD

**Issue by IanHeywood** [ska-sa/tigger#118]
Trying to install current master as follows:

```
$  cd ~/venv/
$  virtualenv -p python3 tigger
$  source tigger/bin/activate
$ cd ~/Software/
$  git clone https://github.com/ska-sa/tigger.git
$  cd tigger/
$  ./install_tigger_ubuntu.sh 
```

Starting tigger gives the following error:

```
$ tigger
Traceback (most recent call last):
  File "/home/ianh/.local/bin/tigger", line 4, in <module>
    __import__('pkg_resources').run_script('astro-tigger==1.6.0', 'tigger')
  File "/home/ianh/venv/tigger/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/home/ianh/venv/tigger/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/home/ianh/venv/tigger/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ianh/venv/tigger/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/home/ianh/venv/tigger/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ianh/venv/tigger/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'astro-tigger==1.6.0' distribution was not found and is required by the application
```

and also:

```
$ pip install astro-tigger==1.6.0
ERROR: Could not find a version that satisfies the requirement astro-tigger==1.6.0 (from versions: 1.3.3, 1.3.5, 1.3.9, 1.3.10, 1.4.0, 1.5.0)
ERROR: No matching distribution found for astro-tigger==1.6.0
```

**Comment by razman786** [comment]
@IanHeywood - could you attach the installer's log files (`tigger_installer.log` and `tigger_installer.err`) here as well please?

**Comment by IanHeywood** [comment]
Sure, here you go...

[tigger_installer.log](https://github.com/ska-sa/tigger/files/6884664/tigger_installer.log)
[tigger_installer.err.txt](https://github.com/ska-sa/tigger/files/6884665/tigger_installer.err.txt)

**Comment by razman786** [comment]
@IanHeywood - This is the manual method for your setup on 18.04, while I create a PR to fix this issue:

First without a venv:
```
cd ~/Software
git clone https://github.com/ska-sa/tigger.git
sudo apt -y install python3-pip
sudo apt -y install python3-pyqt5.qtsvg python3-pyqt5.qtopengl libqwt-qt5-6
cd ~/Software/tigger
sudo dpkg -i ubuntu_18_04_deb_pkg/python3-pyqt5.qwt_2.00.00_amd64.deb
```
venv setup:
```
cd ~/venv
virtualenv -p python3 tigger_160
source tigger_160/bin/activate
cd ~/Software/tigger
pip3 install vext.pyqt5
pip3 install .
```

Then typing `tigger` should work fine. 

If you get some message about missing dependencies you might need to check `vext` is running with `vext -l`. If it shows `[disabled]` then enable it with `vext -e`

**Comment by IanHeywood** [comment]
<img width="1440" alt="Screen Shot 2021-07-27 at 17 08 48" src="https://user-images.githubusercontent.com/6533799/127188890-74197952-624e-4cd6-92a2-948afcc85234.png">

Success! Cheers.

**Comment by razman786** [comment]
I am reopening this issue to link the PR that has the fixes.

**Comment by razman786** [comment]
Closing as this is included in https://github.com/ska-sa/tigger/pull/114
