### ISSUE TITLE
Truncated FITS file: error not reported properly, fails mysteriously down the line later

### ISSUE THREAD

**Issue by SpheMakh** [ska-sa/tigger#39]
```
Warning: File may have been truncated: actual file length (189743104) is smaller than the expected size (637634880)
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Images/Manager.py", line 128, in loadImage
    image = SkyImage.FITSImagePlotItem(str(filename));
  File "/home/makhathini/meqtrees/tigger/Tigger/Images/SkyImage.py", line 553, in __init__
    self.read(filename,hdu);
  File "/home/makhathini/meqtrees/tigger/Tigger/Images/SkyImage.py", line 568, in read
    data = hdu.data;
  File "/usr/lib/pymodules/python2.7/pyfits/core.py", line 4110, in __getattr__
    raw_data.shape=dims
ValueError: total size of new array must be unchanged
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Warning: File may have been truncated: actual file length (189743104) is smaller than the expected size (637634880)
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Images/Manager.py", line 128, in loadImage
    image = SkyImage.FITSImagePlotItem(str(filename));
  File "/home/makhathini/meqtrees/tigger/Tigger/Images/SkyImage.py", line 553, in __init__
    self.read(filename,hdu);
  File "/home/makhathini/meqtrees/tigger/Tigger/Images/SkyImage.py", line 568, in read
    data = hdu.data;
  File "/usr/lib/pymodules/python2.7/pyfits/core.py", line 4110, in __getattr__
    raw_data.shape=dims
ValueError: total size of new array must be unchanged
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
Traceback (most recent call last):
  File "/home/makhathini/meqtrees/tigger/Tigger/Plot/SkyModelPlot.py", line 1561, in _plotProvisionalZoom
    self._provisional_zoom_level += level;
AttributeError: 'SkyModelPlotter' object has no attribute '_provisional_zoom_level'
```

**Comment by razman786** [comment]
Closing as fix is in https://github.com/ska-sa/tigger/pull/114
