### ISSUE TITLE
import Tigger fails with NameError: name 'pkg_resources' is not defined

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/tigger#65]
Running tigger from own repo (@modhurita reporting) fails with the above error. 

```
Traceback (most recent call last):
  File "/home/mitra/MeqTrees/pyxis/Pyxis/Internals.py", line 816, in load_package
    exec(file(filename),Pyxis.Context);
  File "./pyxis-RP3C147.py", line 11, in <module>
    import mqt,stefcal,imager,lsm,std,ms,Tigger
  File "/home/mitra/MeqTrees/meqtrees-cattery/Cattery/Pyxides/stefcal.py", line 3, in <module>
    import std,ms,lsm,mqt,im
  File "/home/mitra/MeqTrees/pyxis/Pyxides/lsm.py", line 6, in <module>
    import Tigger
  File "/home/mitra/MeqTrees/tigger/Tigger/__init__.py", line 38, in <module>
    except pkg_resources.DistributionNotFound:
NameError: name 'pkg_resources' is not defined
2016/03/16 13:19:32 ABORT: PYXIS: error parsing ./pyxis-RP3C147.py, see output above and/or log for details
```

Two issues here: ``import pkg_resources`` is not done, and anyway pkg_resources is an extra package that we shouldn't depend on (@gijzelaerr?)

**Comment by gijzelaerr** [comment]
oops, fixed this too fast. pkg_resources is part of setuptools, which is used to install tigger so it should be installed.
