### ISSUE TITLE
Startup error: pixmaps

### ISSUE THREAD

**Issue by IanHeywood** [ska-sa/tigger#82]
Getting this all of a sudden when I try to run Tigger. Not sure what I might have done to cause it...

```
ianh@nerv:~$ tigger 
Welcome to Tigger using svn version
Please wait a second while the GUI starts up.
Traceback (most recent call last):
  File "/home/ianh/meqtrees/tigger/Tigger/bin/tigger", line 77, in <module>
    from Tigger import pixmaps
ImportError: cannot import name pixmaps
```

Suggestions most welcome.

Cheers.

**Comment by o-smirnov** [comment]
What's your PYTHONPATH looking like? Looks like it's picking up the wrong Tigger directory somehow. Do this in python:
```
import Tigger
print Tigger.__file__
```
Does the path correspond to your Tigger install? Is there a pixmaps.py under it?

**Comment by IanHeywood** [comment]
PYTHONPATH looks sane to me:

```
ianh@nerv:~$ echo $PYTHONPATH
:/home/ianh/Purr:/home/ianh/meqtrees/meqtrees-timba/install/symlinked-release/libexec/python:.:/home/ianh/meqtrees/owlcat:/home/ianh/meqtrees/pyxis:/home/ianh/meqtrees/kittens:/home/ianh/meqtrees/purr:/home/ianh/meqtrees/tigger:
```

Executable is being picked up from the right place:

```
ianh@nerv:~$ which tigger
/home/ianh/meqtrees/tigger/Tigger/bin/tigger
ianh@nerv:~$ tigger
Welcome to Tigger using svn version
Please wait a second while the GUI starts up.
Traceback (most recent call last):
  File "/home/ianh/meqtrees/tigger/Tigger/bin/tigger", line 77, in <module>
    from Tigger import pixmaps
```

But then this is happening:

```
In [1]: import Tigger

In [2]: print Tigger.__file__
/usr/lib/python2.7/dist-packages/Tigger/__init__.pyc
```

and that location does not contain pixmaps.py:

```
ianh@nerv:~$ ls /usr/lib/python2.7/dist-packages/Tigger
AboutDialog.py   Coordinates.py   Images        MainWindow.py   Plot                  SkyModelTreeWidget.py   tigger.conf   Widgets.py
AboutDialog.pyc  Coordinates.pyc  __init__.py   MainWindow.pyc  SiameseInterface.py   SkyModelTreeWidget.pyc  Tools         Widgets.pyc
bin              icons            __init__.pyc  Models          SiameseInterface.pyc  tigger                  version_info
```

however neither does the 'correct' location:

```
ianh@nerv:~$ ls /home/ianh/meqtrees/tigger/Tigger
AboutDialog.py   Coordinates.py   Images        MainWindow.py   Plot                  SkyModelTreeWidget.py   tigger.conf   Widgets.py
AboutDialog.pyc  Coordinates.pyc  __init__.py   MainWindow.pyc  SiameseInterface.py   SkyModelTreeWidget.pyc  Tools         Widgets.pyc
bin              icons            __init__.pyc  Models          SiameseInterface.pyc  tigger                  version_info
```

The pixmaps.py file exists in 'kittens':

```
ianh@nerv:~$ ls /home/ianh/meqtrees/kittens/Kittens/
config.py  config.pyc  __init__.py  __init__.pyc  pixmaps.py  pixmaps.pyc  utils.py  utils.pyc  widgets.py  widgets.pyc
```

**Comment by IanHeywood** [comment]
```
In [1]: import Tigger

In [2]: dir(Tigger)
Out[2]: 
['Models',
 '__builtins__',
 '__doc__',
 '__file__',
 '__name__',
 '__package__',
 '__path__',
 'import_pyfits',
 'listFormats',
 'load',
 'matplotlib_nuked',
 'nuke_matplotlib',
 'release_string',
 'save',
 'startup_dprint',
 'startup_dprintf',
 'svn_revision_html',
 'svn_revision_string',
 'sys',
 'version_info']
```

Literally no idea what's caused this. I've reverted to the standard package version in /usr/bin/tigger.

**Comment by o-smirnov** [comment]
OK assume it was just a misconfigured system.
