### ISSUE TITLE
Unicode error when displaying extended sources

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/tigger#97]
Looks like some errors crept in during the Python 3 transition. In particular, getting this:
```
$ cat >1.txt
#format: name ra_d dec_d i emaj_s emin_s pa_d
A 0.0 0.0 1.0 10.0 5.0 0.0
^D
$ tigger 1.txt
<funky error>
```
This is no doubt due to it trying to insert Unicode characters into a string, but I'm not sure exactly how to fix it.

**Comment by gijzelaerr** [comment]
what is the funky error you are seeing? For me this just works...

**Comment by gijzelaerr** [comment]
i can even put unicode (😊) inside the model.

**Comment by o-smirnov** [comment]
Where funky error is:
```
oms@jakob:~/tmp$ tigger 1.txt 
Welcome to Tigger 1.4.0
Please wait a second while the GUI starts up.
/home/oms/.local/lib/python2.7/site-packages/pyfits/__init__.py:21: PyFITSDeprecationWarning: PyFITS is deprecated, please use astropy.io.fits
  PyFITSDeprecationWarning)  # noqa
('Loading model', '1.txt')
Traceback (most recent call last):
  File "/home/oms/tigger/TigGUI/tigger", line 123, in <module>
    mainwin.openFile(mod,show=False)
  File "/home/oms/tigger/TigGUI/MainWindow.py", line 473, in openFile
    self.setModel(model)
  File "/home/oms/tigger/TigGUI/MainWindow.py", line 398, in setModel
    self.tw.setModel(self.model)
  File "/home/oms/tigger/TigGUI/SkyModelTreeWidget.py", line 194, in setModel
    self._refreshModel(SkyModel.UpdateAll)
  File "/home/oms/tigger/TigGUI/SkyModelTreeWidget.py", line 212, in _refreshModel
    items = [SkyModelTreeWidgetItem(src) for src in self.model.sources]
  File "/home/oms/tigger/TigGUI/SkyModelTreeWidget.py", line 318, in __init__
    self.setSource(src)
  File "/home/oms/tigger/TigGUI/SkyModelTreeWidget.py", line 395, in setSource
    shapestr = shape.strDesc(delimiters=('"', chr(0xD7), chr(0x21BA), chr(0xB0)))
ValueError: chr() arg not in range(256)
Error loading model 1.txt
```

**Comment by gijzelaerr** [comment]
this issue has already been reported and solved in the `modernize` branch

https://github.com/ska-sa/tigger/pull/95#issuecomment-391007016
